name = "ord"
compatibility_date = "2024-12-25"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ord"

[env.production.build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.production.build.upload]
format = "service-worker"
dir = "./dist"
main = "./dist/index.html"

[[env.production.routes]]
pattern = "ord.pages.dev/*"
zone_name = ""

# For local development
[env.development]
name = "ord-dev"

[env.development.build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages-specific configuration
pages_build_output_dir = "./dist"